name: SMARTS CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-18.04
    container: huaweinoah/smarts:v0.4.6
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Package Setup
        run: |
          /usr/bin/Xorg \
            -noreset \
            +extension GLX \
            +extension RANDR \
            +extension RENDER \
            -logfile ./xdummy.log \
            -config /etc/X11/xorg.conf :1 &
          cd $GITHUB_WORKSPACE
          pip install --upgrade pip
          pip install wheel
          pip install -r requirements.txt
          pip install --upgrade -e .[train]
      - name: Run smoke tests
        run: |
          cd $GITHUB_WORKSPACE
          make test

