name: SMARTS CI

on: [push]

jobs:
  test-formatting:
    runs-on: ubuntu-18.04
    container: huaweinoah/smarts:v0.4.6
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Black code formatter
        run: |
          cd $GITHUB_WORKSPACE
          pip install --upgrade pip
          pip install black==19.10b0
          apt-get update && apt-get install -y curl
          curl -sL https://deb.nodesource.com/setup_14.x | bash -
          apt-get install -y nodejs
          black --check .
          npx prettier --check envision/web/src

  test-requirements:
    runs-on: ubuntu-18.04
    container: huaweinoah/smarts:v0.4.6
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test Pip Packages
        run: |
          cd $GITHUB_WORKSPACE
          ./test_pip_packages.sh
